### ISSUE TITLE
Publishing issues

### ISSUE THREAD

**Issue by Alkur** [dsuryd/dotnetify-react-demo#1]
Hi,
I've built an application based in your dotnetify-react-demo/LiveChart/

It runs perfectly in development server (run with npm start), but I'm having problems to publish it on a production Server.

I've run:
dotnet publish -c Release
npm run build

But as far as I see, those create two independant applications one for the js + css + html, and the second one for the dotnet dlls.

Can you please explain a bit how to publish this example as a single one application on IIS (I already installed DotNetCoreWindowsHosting)?

I've also tried to manually add /bin folder created by "dotnet publish"  with no luck.
In the console I get: 

Information: Normalizing '/dotnetify' to 'http://localhost/dotnetify'    signalR-netcore.js:2462
Error: Failed to start the connection. SyntaxError: Unexpected end of JSON input    signalR-netcore.js:2462 

Fort sure my application is not under http://localhost/dotnetify, I'm trying to deploy it on http://localhost/testapplication

Thanks.

**Comment by dsuryd** [comment]
Hi,  since you're targetting IIS, it would be better to create an ASP.NET Core Web App project and use Visual Studio 2017's "Publish" option.  See the example project in [dotnetify-react-demo-vs2017](https://github.com/dsuryd/dotnetify-react-demo-vs2017/tree/master/LiveChart).  

I used Task Runner Explorer to build the bundle, but if you use npm directly, you can just drop the files onto the wwwroot folder.

**Comment by dsuryd** [comment]
Try this:
https://github.com/dsuryd/dotnetify-react-demo-vs2017/blob/master/LiveChart/IISPublishingSteps.md

**Comment by Elijah23Johnson** [comment]
Hello

I am exploring server side rendering react components and must say that your starter is brilliant (dotnet new -i DotNetify.React.Template). I have made some modifications and tried to publish to an azure web app but got the following errors.

 fail: Microsoft.AspNetCore.NodeServices[0]
      node.js:384
fail: Microsoft.AspNetCore.NodeServices[0]
                var b = process.binding('signal_watcher');
fail: Microsoft.AspNetCore.NodeServices[0]
                                ^
fail: Microsoft.AspNetCore.NodeServices[0]
      Error: No such module
fail: Microsoft.AspNetCore.NodeServices[0]
          at EventEmitter.<anonymous> (node.js:384:27)
fail: Microsoft.AspNetCore.NodeServices[0]
          at Object.exitWhenParentExits (D:\local\Temp\m5fp3xto.sxc:336:18)
fail: Microsoft.AspNetCore.NodeServices[0]
          at Object.<anonymous> (D:\local\Temp\m5fp3xto.sxc:129:24)
fail: Microsoft.AspNetCore.NodeServices[0]
          at __webpack_require__ (D:\local\Temp\m5fp3xto.sxc:20:30)
fail: Microsoft.AspNetCore.NodeServices[0]
          at Object.<anonymous> (D:\local\Temp\m5fp3xto.sxc:47:19)
fail: Microsoft.AspNetCore.NodeServices[0]
          at __webpack_require__ (D:\local\Temp\m5fp3xto.sxc:20:30)
fail: Microsoft.AspNetCore.NodeServices[0]
          at D:\local\Temp\m5fp3xto.sxc:40:18
fail: Microsoft.AspNetCore.NodeServices[0]
          at Object.<anonymous> (D:\local\Temp\m5fp3xto.sxc:41:11)
fail: Microsoft.AspNetCore.NodeServices[0]
          at Module._compile (module.js:446:26)
fail: Microsoft.AspNetCore.NodeServices[0]
          at Object..js (module.js:464:10)
Application startup exception: System.AggregateException: One or more errors occurred. (Attempt to connect to Node timed out after 60000ms.
) ---> Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Attempt to connect to Node timed out after 60000ms.

   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at WebReactServerSide.Startup.Configure(IApplicationBuilder app) in C:\Users\Elijah\Documents\Visual Studio 2017\Projects\WebReactServerSide\server\Startup.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Attempt to connect to Node timed out after 60000ms.

   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)<---

crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.AggregateException: One or more errors occurred. (Attempt to connect to Node timed out after 60000ms.
) ---> Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Attempt to connect to Node timed out after 60000ms.

   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at WebReactServerSide.Startup.Configure(IApplicationBuilder app) in C:\Users\Elijah\Documents\Visual Studio 2017\Projects\WebReactServerSide\server\Startup.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Attempt to connect to Node timed out after 60000ms.

   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)<---

Hosting environment: Production
Content root path: D:\home\site\wwwroot
Now listening on: http://127.0.0.1:30175
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://publicwebreactserverside.azurewebsites.net/favicon.ico  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 19.0981ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://127.0.0.1:30175/iisintegration  0
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3105ms 500 text/html; charset=utf-8


Any Ideas?

**Comment by dsuryd** [comment]
Hi, it’s been a while since I played around with Azure.  Did you try to publish the original template as is, and if so, did it have the same error?

**Comment by bugged84** [comment]
@dsuryd I'm having the same issue @PosSoolutions, and yes I deployed your original template out of box.

**Comment by Elijah23Johnson** [comment]
Yes! The error persisted in both scenarios, out of the box and even after some minor modifications. I was however able to get it to build in IIS after upgrading to the .Net 2.1 run time. It seems like the signalR has its draw backs especially in azure. I'm assuming due to the constant connection it creates between client and server. Produces a high volume of latency on the server which then wakes up the allusive 502.5 bug. Failure to start the .Net process.

**Comment by Elijah23Johnson** [comment]
After digging down into the problem more the actual point of failure took place at the point when the node process was invoked. With 
```
fail: Microsoft.AspNetCore.NodeServices[0]
node.js:384
```
This was also the case in IIS at first until I Included the node_models and pointed the .Net dependencies in the right location.
One doesn't have the ease of moving files and pointing dependencys around in azure so out of the box it does not build. And I can guarantee its the build paths.

**Comment by dsuryd** [comment]
AspNetCore.NodeServices is used only for webpack build and hot reload during development.  I suspect the template’s Startup.cs only needs to be cleared of using WebpackDevMiddleware on production build.

**Comment by Elijah23Johnson** [comment]
You are absolutely right. brilliant!

**Comment by Elijah23Johnson** [comment]
O Im sorry that was not your template I was able to eventually get it to build and publish utilizing .NetIfy Libraries and Microsoft standard ASP.NET Core template. 

![build](https://user-images.githubusercontent.com/31963164/46921035-40e66b80-cfab-11e8-9e75-cf0d299e2270.gif)

**Comment by bugged84** [comment]
@PosSoolutions sorry forgot to mention a couple days ago that if you're using the dotnetify template then you have to add `if (env.IsDevelopment())` around the webpack middleware in the `Startup.cs` file. Other than that, his template worked out-of-the-box to get running in Azure App Service.

@dsuryd maybe you can add that condition to the template. I spent several hours of debugging that day in App Service logs to find the node error and relate that back to the webpack middleware. Updating the template might save people some time.

**Comment by bugged84** [comment]
@dsuryd created a PR for this: https://github.com/dsuryd/dotNetify-Elements/pull/23
